/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AirlineTable: typeof import('./src/components/map/AirlineTable.vue')['default']
    AirportRateTable: typeof import('./src/components/map/AirportRateTable.vue')['default']
    BacklogFlightPanel: typeof import('./src/components/map/BacklogFlightPanel.vue')['default']
    BacklogPieChart: typeof import('./src/components/dashboard/BacklogPieChart.vue')['default']
    BarChart3D: typeof import('./src/components/dashboard/BarChart3D.vue')['default']
    Chart: typeof import('./src/components/chart.vue')['default']
    CorridorFlowChart: typeof import('./src/components/map/CorridorFlowChart.vue')['default']
    CumulativeDelay: typeof import('./src/components/dashboard/CumulativeDelay.vue')['default']
    CustomTag: typeof import('./src/components/CustomTag.vue')['default']
    DashboardPanel: typeof import('./src/components/dashboard/DashboardPanel.vue')['default']
    DataGrid: typeof import('./src/components/dataGrid.vue')['default']
    DelayBarChart: typeof import('./src/components/dashboard/DelayBarChart.vue')['default']
    DemoForm: typeof import('./src/components/demoForm.vue')['default']
    Drawer: typeof import('./src/components/drawer.vue')['default']
    DxLinkButton: typeof import('./src/components/DxLinkButton.vue')['default']
    DxPagination: typeof import('./src/components/DxPagination.vue')['default']
    DxTable: typeof import('./src/components/DxTable.vue')['default']
    Echarts: typeof import('./src/components/echarts.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    FlightExecutionPanel: typeof import('./src/components/map/FlightExecutionPanel.vue')['default']
    FlightNormalRatePanel: typeof import('./src/components/map/FlightNormalRatePanel.vue')['default']
    FlightRate: typeof import('./src/components/dashboard/FlightRate.vue')['default']
    FlightTable: typeof import('./src/components/dashboard/FlightTable.vue')['default']
    FlowTable: typeof import('./src/components/FlowTable.vue')['default']
    FlyDelayTimeCharts: typeof import('./src/components/FlyDelayTimeCharts.vue')['default']
    Form: typeof import('./src/components/form.vue')['default']
    FormDialog: typeof import('./src/components/FormDialog.vue')['default']
    Grid: typeof import('./src/components/grid.vue')['default']
    Home: typeof import('./src/components/home.vue')['default']
    IconSelector: typeof import('./src/components/IconSelector.vue')['default']
    Menu: typeof import('./src/components/menu.vue')['default']
    MicroApp: typeof import('./src/components/MicroApp.vue')['default']
    MixedChart: typeof import('./src/components/map/MixedChart.vue')['default']
    PopUp: typeof import('./src/components/popUp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RouteStatChart: typeof import('./src/components/RouteStatChart.vue')['default']
    Tab: typeof import('./src/components/tab.vue')['default']
    TechBorder: typeof import('./src/components/TechBorder.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    TreeListDemo: typeof import('./src/components/TreeListDemo.vue')['default']
    Upload: typeof import('./src/components/upload.vue')['default']
    Vue2Sub: typeof import('./src/components/vue2Sub.vue')['default']
    Vue3Sub: typeof import('./src/components/vue3Sub.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
